name: react-native-android-build-apk
on:
  push:
    branches:
      - main
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decode Keystore
        id: decode_keystore
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > release.keystore.asc
          gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch release.keystore.asc > android/metawallet.keystore
          pwd
          ls
          
      - name: Build Android Release
        run: |
          cd android && ls
